# Usa un'immagine Node.js leggera
FROM node:18-alpine

# Imposta la directory di lavoro
WORKDIR /app

# Copia il file package.json
COPY package.json package-lock.json ./

# Installa le dipendenze
RUN npm install --omit=dev

# Copia il codice sorgente
COPY . .

# Espone la porta del Notification Service
EXPOSE 5000

# Avvia il servizio
CMD ["node", "server.js"]
