# Usa un'immagine Node.js leggera
FROM node:18-alpine

# Imposta la directory di lavoro all'interno del container
WORKDIR /app

# Copia il file package.json e package-lock.json
COPY package.json package-lock.json ./

# Installa le dipendenze
RUN npm install --omit=dev

# Copia tutto il codice sorgente
COPY . .

# Espone la porta del servizio API Gateway
EXPOSE 8080

# Avvia l'API Gateway
CMD ["node", "server.js"]
