# Usa un'immagine Node.js leggera
FROM node:18-alpine

# Imposta la directory di lavoro
WORKDIR /app

# Copia i file package.json e package-lock.json
COPY package.json package-lock.json ./

# Installa solo le dipendenze di produzione
RUN npm install --omit=dev

# Copia il codice sorgente
COPY . .

# Espone la porta del servizio User Service
EXPOSE 3001

# Avvia l'applicazione
CMD ["node", "server.js"]
