# Traefik v3 config statica
entryPoints:
  web:
    address: ":${WEB_PORT}"
  websecure:
    address: ":${WEBSECURE_PORT}"

providers:
  docker:
    exposedByDefault: false
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

api:
  dashboard: true

log:
  level: INFO

accessLog: {}
