# Usa un'immagine Node.js leggera
FROM node:18-alpine

# Imposta la directory di lavoro
WORKDIR /app

# Copia il file package.json
COPY package.json package-lock.json ./

# Installa solo le dipendenze di produzione
RUN npm install --omit=dev

# Copia il codice sorgente
COPY . .

# Espone la porta del Question Service
EXPOSE 3002

# Avvia il servizio
CMD ["node", "server.js"]
