version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth
      - user-service
      - question-service
      - voting-service
    environment:
      - AUTH0_DOMAIN=your-auth0-domain
      - AUTH0_CLIENT_ID=your-client-id
      - AUTH0_CLIENT_SECRET=your-client-secret

  user-service:
    build: ./user-service
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://root:root_password@mysql:3306/voting_app

  question-service:
    build: ./question-service
    environment:
      - OPENAI_API_KEY=your-openai-api-key
    depends_on:
      - mysql

  voting-service:
    build: ./voting-service
    depends_on:
      - mysql
      - user-service

  notification-service:
    build: ./notification-service
    ports:
      - "5000:5000"

  mysql:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=voting_app
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:

